// ESLint Flat Config (TypeScript / ブラウザ)
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        crypto: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        HTMLCollection: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        JSON: "readonly",
        Array: "readonly",
        Object: "readonly",
        Number: "readonly",
        String: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        Boolean: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        URLSearchParams: "readonly",
        Image: "readonly",
        reportError: "readonly",
      },
    },
    files: ["src/**/*.ts"],
  }
);
